# Site settings
name: Go For It
email: percyan111@gmail.com
author: percyan
url: https://percyi.github.io
resume_site: https://www.percyi.site/percy-resume/
github: https://github.com/percyi/
baseurl: ""
description: Knowledge is power
meta_description: percyan;个人博客;学如逆水行舟，不进则退。学无止境，分享知识，经验，见解
motto: It's our wits that make us stronger.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: percyi
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : percyan
    disqus :
        short_name : percyan
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light